name: Symfony compatibility

on:
    push:
        branches:
            - 3.*
    pull_request:
        branches:
            - 3.*

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - php: '8.2'
                      symfony: '7.4'
                    - php: '8.3'
                      symfony: '7.4'
                    - php: '8.4'
                      symfony: '7.4'
                    - php: '8.4'
                      symfony: '8.1'
        steps:
            - name: Checkout SDK
              uses: actions/checkout@v4
              with:
                  path: sdk

            - name: Branch name
              run: echo "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Check php version
              run: php -v

            - name: Check composer version
              run: composer --version

            - name: Install Symfony ${{matrix.symfony}}
              run: composer create-project symfony/skeleton:"${{matrix.symfony}}.*" app

            - name: Check Symfony version
              run: bin/console about
              working-directory: app

            - name: Install sdk
              working-directory: app
              run: |
                  composer config repositories.sdk path ../sdk
                  composer require --prefer-dist --no-progress 'dokobit/ws-api-sdk-php:@dev'
